name: Destroy AWS Resources 

on:
    schedule:
        - cron: '0 12 * * *'

jobs: 
    terraform:
        name: Destroy AWS Resources with Terraform
        runs-on: ubuntu-latest

        steps:
            # Retrieve environment variables
            - name: Retrieve environment variables
              uses: actions/checkout@v3

            # Log into the Terraform User
            - name: Configure AWS Credentials 
              uses: aws-actions/configure-aws-credentials@v2
              with: 
                aws-access-key-id: ${{secrets.AWS_ACCESS_KEY}}
                aws-secret-access-key: ${{secrets.AWS_ACCESS_KEY_SECRET}}
                aws-region: ${{secrets.AWS_REGION}}

            # Setup Terraform 
            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v2
              with:
                terraform_version: ${{secrets.TERRAFORM_VERSION}}
             
            # Destroy resources
            - name: Destroy resources
              run: terraform destroy -auto-approve 