name: Terraform CI/CD

on:
    push:
        branches:
            - main


jobs:
    terraform:
        name: Run Terraform CI/CD
        runs-on: ubuntu-latest 

        steps:
            # Retrieve vars from env 
            - name: Retrieve env variables 
              uses: actions/checkout@v3
