name: Terraform CI/CD

on:
    push:
        branches:
            - main


jobs:
    terraform:
        name: Run Terraform CI/CD
        runs-on: ubuntu-latest 

        steps:
            # Retrieve vars from env 
            - name: Retrieve env variables 
              uses: actions/checkout@v3

            # Configure AWS Access Credentials 
            - name: Configure AWS Access Credentials
              uses: aws-actions/configure-aws-credentials@v2
              with:
                aws-access-key-id: ${{secrets.AWS_ACCESS_KEY}}
                aws-secret-access-key: ${{secrets.AWS_ACCESS_KEY_SECRET}}
                aws-region: ${{secrets.AWS_REGION}}

            # Set up and configure Terraform 
            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v2
              with:
                terraform_version: ${{secrets.TERRAFORM_VERSION}}

            # Initialize Terraform
            - name: Terraform Init
              run: terraform init 

            # Plan the Terraform changes 
            - name: Terraform plan
              run: terraform plan -out=tfplan

            # Terraform Apply 
            - name: Terraform
              run: terraform apply -auto-approve tfplan 



            

